version: "3.7"

services:
  db:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ygbouri
      - POSTGRES_USER=ygbouri
      - POSTGRES_PASSWORD=ygbouri
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080

volumes:
  database:
